# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3342e9faedd8fe9ea360c0af568d00a46917923791c23e144d66849b272d2ff63e743f9bb209dab7d6e732bb5f919e46e3fe552b8919140805bb89c346e68876,
  # auth0_client_id: qX7DAeggjWSJyDFmB5jiqXl2nIGKKWeb
  # auth0_client_secret: MF8tzfW7SEF44fq3VJzLfi69FYx-jpTfdbDCQsj_k9Y4sTKbthQMYBVKVOOZBhdq

test:
  secret_key_base: eaab008cd2ab64704b1a962f290aca435fd35934382b747c57fc8d5f4808e49dedd173a78556837abca3fc122cb3b945099726c4bb981de3b893aef2fbba6e11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ENV["SECRET_KEY_BASE"]
  # auth0_client_id: qX7DAeggjWSJyDFmB5jiqXl2nIGKKWeb
  # auth0_client_secret: MF8tzfW7SEF44fq3VJzLfi69FYx-jpTfdbDCQsj_k9Y4sTKbthQMYBVKVOOZBhdq
